const allproducts = [
  {
    id: 1,
    image: "/images/emerald.png",
    title: "Emerald Diamond Earrings",
    price: "15,000",
    cart: "/images/cart-plus-alt.svg",
  },
  {
    id: 2,
    image: "/images/bag.png",
    title: "Holder  Black  Leather Bag",
    price: "10,000",
    cart: "/images/cart-plus-alt.svg",
  },
  {
    id: 3,
    image: "/images/redshoes.png",
    title: "Red Pump Heelss",
    price: "25,000",
    cart: "/images/cart-plus-alt.svg",
  },
  {
    id: 4,
    image: "/images/rings.png",
    title: "Knuckles  Rings",
    price: "5,000",
    cart: "./images/cart-plus-alt.svg",
  },
  {
    id: 5,
    image: "/images/gown.png",
    title: "Flower Yellow Dress",
    price: "13,000",
    cart: "./images/cart-plus-alt.svg",
  },
  {
    id: 6,
    image: "/images/sneakers.png",
    title: "Casual Breathable Canvas",
    price: "25,000",
    cart: "./images/cart-plus-alt.svg",
  },
  {
    id: 7,
    image: "/images/necklace.png",
    title: "Star Shaped  Chain",
    price: "3,500",
    cart: "/images/cart-plus-alt.svg",
  },
  {
    id: 8,
    image: "/images/suit.png",
    title: "Mens  Complete  suit set",
    price: "25,000",
    cart: "/images/cart-plus-alt.svg",
  },
  {
    id: 9,
    image: "/images/emerald.png",
    title: "Emerald Diamond Earrings",
    price: "15,000",
    cart: "/images/cart-plus-alt.svg",
  },
  {
    id: 10,
    image: "/images/bag.png",
    title: "Holder  Black  Leather Bag",
    price: "10,000",
    cart: "/images/cart-plus-alt.svg",
  },
  {
    id: 11,
    image: "/images/redshoes.png",
    title: "Red Pump Heelss",
    price: "25,000",
    cart: "/images/cart-plus-alt.svg",
  },
  {
    id: 12,
    image: "/images/rings.png",
    title: "Knuckles  Rings",
    price: "5,000",
    cart: "./images/cart-plus-alt.svg",
  },
  {
    id: 13,
    image: "/images/gown.png",
    title: "Flower Yellow Dress",
    price: "13,000",
    cart: "./images/cart-plus-alt.svg",
  },
  {
    id: 14,
    image: "/images/sneakers.png",
    title: "Casual Breathable Canvas",
    price: "25,000",
    cart: "./images/cart-plus-alt.svg",
  },
  {
    id: 15,
    image: "/images/necklace.png",
    title: "Star Shaped  Chain",
    price: "3,500",
    cart: "/images/cart-plus-alt.svg",
  },
  {
    id: 16,
    image: "/images/suit.png",
    title: "Mens  Complete  suit set",
    price: "25,000",
    cart: "/images/cart-plus-alt.svg",
  },
  {
    id: 17,
    image: "/images/emerald.png",
    title: "Emerald Diamond Earrings",
    price: "15,000",
    cart: "/images/cart-plus-alt.svg",
  },
  {
    id: 18,
    image: "/images/bag.png",
    title: "Holder  Black  Leather Bag",
    price: "10,000",
    cart: "/images/cart-plus-alt.svg",
  },
  {
    id: 19,
    image: "/images/redshoes.png",
    title: "Red Pump Heelss",
    price: "25,000",
    cart: "/images/cart-plus-alt.svg",
  },
  {
    id: 20,
    image: "/images/rings.png",
    title: "Knuckles  Rings",
    price: "5,000",
    cart: "./images/cart-plus-alt.svg",
  },
  {
    id: 21,
    image: "/images/gown.png",
    title: "Flower Yellow Dress",
    price: "13,000",
    cart: "./images/cart-plus-alt.svg",
  },
  {
    id: 22,
    image: "/images/sneakers.png",
    title: "Casual Breathable Canvas",
    price: "25,000",
    cart: "./images/cart-plus-alt.svg",
  },
  {
    id: 23,
    image: "/images/necklace.png",
    title: "Star Shaped  Chain",
    price: "3,500",
    cart: "/images/cart-plus-alt.svg",
  },
  {
    id: 24,
    image: "/images/suit.png",
    title: "Mens  Complete  suit set",
    price: "25,000",
    cart: "/images/cart-plus-alt.svg",
  },
  
];

export default allproducts;
